# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TankCalcStacked.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(1109, 1130)
        StackedWidget.setAutoFillBackground(True)
        self.TankDesignData = QtWidgets.QWidget()
        self.TankDesignData.setObjectName("TankDesignData")
        self.Tankspecficationdata_2 = QtWidgets.QLabel(self.TankDesignData)
        self.Tankspecficationdata_2.setGeometry(QtCore.QRect(90, 120, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tankspecficationdata_2.setFont(font)
        self.Tankspecficationdata_2.setObjectName("Tankspecficationdata_2")
        self.Tanknumber_2 = QtWidgets.QLabel(self.TankDesignData)
        self.Tanknumber_2.setGeometry(QtCore.QRect(90, 200, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tanknumber_2.setFont(font)
        self.Tanknumber_2.setObjectName("Tanknumber_2")
        self.Typeoftank_2 = QtWidgets.QLabel(self.TankDesignData)
        self.Typeoftank_2.setGeometry(QtCore.QRect(90, 260, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Typeoftank_2.setFont(font)
        self.Typeoftank_2.setObjectName("Typeoftank_2")
        self.Itemname_2 = QtWidgets.QLabel(self.TankDesignData)
        self.Itemname_2.setGeometry(QtCore.QRect(90, 340, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Itemname_2.setFont(font)
        self.Itemname_2.setObjectName("Itemname_2")
        self.Designcode_2 = QtWidgets.QLabel(self.TankDesignData)
        self.Designcode_2.setGeometry(QtCore.QRect(90, 410, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Designcode_2.setFont(font)
        self.Designcode_2.setObjectName("Designcode_2")
        self.heading = QtWidgets.QLabel(self.TankDesignData)
        self.heading.setGeometry(QtCore.QRect(260, 30, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setAutoFillBackground(True)
        self.heading.setFrameShape(QtWidgets.QFrame.Box)
        self.heading.setObjectName("heading")
        self.next = QtWidgets.QPushButton(self.TankDesignData)
        self.next.setGeometry(QtCore.QRect(360, 650, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next.setFont(font)
        self.next.setObjectName("next")
        self.label_3 = QtWidgets.QLabel(self.TankDesignData)
        self.label_3.setGeometry(QtCore.QRect(750, -50, 361, 271))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_3.setObjectName("label_3")
        self.Designcode = QtWidgets.QTextEdit(self.TankDesignData)
        self.Designcode.setGeometry(QtCore.QRect(380, 410, 341, 51))
        self.Designcode.setObjectName("Designcode")
        self.Itemname = QtWidgets.QTextEdit(self.TankDesignData)
        self.Itemname.setGeometry(QtCore.QRect(380, 340, 341, 51))
        self.Itemname.setObjectName("Itemname")
        self.Typeoftank = QtWidgets.QTextEdit(self.TankDesignData)
        self.Typeoftank.setGeometry(QtCore.QRect(380, 270, 341, 51))
        self.Typeoftank.setObjectName("Typeoftank")
        self.Tanknumber = QtWidgets.QTextEdit(self.TankDesignData)
        self.Tanknumber.setGeometry(QtCore.QRect(380, 200, 341, 51))
        self.Tanknumber.setObjectName("Tanknumber")
        self.Tankspecficationdata = QtWidgets.QTextEdit(self.TankDesignData)
        self.Tankspecficationdata.setGeometry(QtCore.QRect(380, 130, 341, 51))
        self.Tankspecficationdata.setObjectName("Tankspecficationdata")
        StackedWidget.addWidget(self.TankDesignData)
        self.DesignInputParameter = QtWidgets.QWidget()
        self.DesignInputParameter.setObjectName("DesignInputParameter")
        self.heading_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.heading_2.setGeometry(QtCore.QRect(220, 20, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.heading_2.setFont(font)
        self.heading_2.setAutoFillBackground(True)
        self.heading_2.setFrameShape(QtWidgets.QFrame.Box)
        self.heading_2.setObjectName("heading_2")
        self.Nominalcapacity = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.Nominalcapacity.setGeometry(QtCore.QRect(350, 120, 211, 51))
        self.Nominalcapacity.setObjectName("Nominalcapacity")
        self.Nominalcapacity_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.Nominalcapacity_2.setGeometry(QtCore.QRect(120, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Nominalcapacity_2.setFont(font)
        self.Nominalcapacity_2.setObjectName("Nominalcapacity_2")
        self.Insidediameter_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.Insidediameter_2.setGeometry(QtCore.QRect(120, 190, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Insidediameter_2.setFont(font)
        self.Insidediameter_2.setObjectName("Insidediameter_2")
        self.Insidediameter = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.Insidediameter.setGeometry(QtCore.QRect(340, 190, 211, 51))
        self.Insidediameter.setObjectName("Insidediameter")
        self.tankheight_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.tankheight_2.setGeometry(QtCore.QRect(120, 260, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tankheight_2.setFont(font)
        self.tankheight_2.setObjectName("tankheight_2")
        self.tankheight = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.tankheight.setGeometry(QtCore.QRect(290, 260, 211, 51))
        self.tankheight.setObjectName("tankheight")
        self.maximumfillingheight_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.maximumfillingheight_2.setGeometry(QtCore.QRect(120, 330, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.maximumfillingheight_2.setFont(font)
        self.maximumfillingheight_2.setObjectName("maximumfillingheight_2")
        self.maximumfillingheight = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.maximumfillingheight.setGeometry(QtCore.QRect(420, 330, 211, 51))
        self.maximumfillingheight.setObjectName("maximumfillingheight")
        self.Htest_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.Htest_2.setGeometry(QtCore.QRect(120, 400, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Htest_2.setFont(font)
        self.Htest_2.setObjectName("Htest_2")
        self.Htest = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.Htest.setGeometry(QtCore.QRect(210, 400, 211, 51))
        self.Htest.setObjectName("Htest")
        self.infillingrate_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.infillingrate_2.setGeometry(QtCore.QRect(120, 470, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.infillingrate_2.setFont(font)
        self.infillingrate_2.setObjectName("infillingrate_2")
        self.infillingrate = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.infillingrate.setGeometry(QtCore.QRect(300, 470, 211, 51))
        self.infillingrate.setObjectName("infillingrate")
        self.Emptyingrate_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.Emptyingrate_2.setGeometry(QtCore.QRect(120, 540, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Emptyingrate_2.setFont(font)
        self.Emptyingrate_2.setObjectName("Emptyingrate_2")
        self.Emptyingrate = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.Emptyingrate.setGeometry(QtCore.QRect(310, 540, 211, 51))
        self.Emptyingrate.setObjectName("Emptyingrate")
        self.Productdensity20C_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.Productdensity20C_2.setGeometry(QtCore.QRect(120, 610, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Productdensity20C_2.setFont(font)
        self.Productdensity20C_2.setObjectName("Productdensity20C_2")
        self.Productdensity20C = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.Productdensity20C.setGeometry(QtCore.QRect(400, 610, 211, 51))
        self.Productdensity20C.setObjectName("Productdensity20C")
        self.Slopeatthebottom1_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.Slopeatthebottom1_2.setGeometry(QtCore.QRect(120, 680, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Slopeatthebottom1_2.setFont(font)
        self.Slopeatthebottom1_2.setObjectName("Slopeatthebottom1_2")
        self.Slopeatthebottom1 = QtWidgets.QTextEdit(self.DesignInputParameter)
        self.Slopeatthebottom1.setGeometry(QtCore.QRect(400, 680, 211, 51))
        self.Slopeatthebottom1.setObjectName("Slopeatthebottom1")
        self.unit = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit.setGeometry(QtCore.QRect(580, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit.setFont(font)
        self.unit.setObjectName("unit")
        self.unit_2 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_2.setGeometry(QtCore.QRect(570, 190, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_2.setFont(font)
        self.unit_2.setObjectName("unit_2")
        self.unit_3 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_3.setGeometry(QtCore.QRect(520, 260, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_3.setFont(font)
        self.unit_3.setObjectName("unit_3")
        self.unit_4 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_4.setGeometry(QtCore.QRect(650, 330, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_4.setFont(font)
        self.unit_4.setObjectName("unit_4")
        self.unit_5 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_5.setGeometry(QtCore.QRect(440, 400, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_5.setFont(font)
        self.unit_5.setObjectName("unit_5")
        self.unit_6 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_6.setGeometry(QtCore.QRect(530, 470, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_6.setFont(font)
        self.unit_6.setObjectName("unit_6")
        self.unit_7 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_7.setGeometry(QtCore.QRect(540, 540, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_7.setFont(font)
        self.unit_7.setObjectName("unit_7")
        self.unit_8 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_8.setGeometry(QtCore.QRect(630, 610, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_8.setFont(font)
        self.unit_8.setObjectName("unit_8")
        self.unit_9 = QtWidgets.QLabel(self.DesignInputParameter)
        self.unit_9.setGeometry(QtCore.QRect(630, 680, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_9.setFont(font)
        self.unit_9.setObjectName("unit_9")
        self.next_2 = QtWidgets.QPushButton(self.DesignInputParameter)
        self.next_2.setGeometry(QtCore.QRect(540, 830, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next_2.setFont(font)
        self.next_2.setObjectName("next_2")
        self.previous = QtWidgets.QPushButton(self.DesignInputParameter)
        self.previous.setGeometry(QtCore.QRect(270, 830, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous.setFont(font)
        self.previous.setObjectName("previous")
        self.label_4 = QtWidgets.QLabel(self.DesignInputParameter)
        self.label_4.setGeometry(QtCore.QRect(720, -10, 361, 271))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_4.setObjectName("label_4")
        StackedWidget.addWidget(self.DesignInputParameter)
        self.CorrsionAllowance = QtWidgets.QWidget()
        self.CorrsionAllowance.setObjectName("CorrsionAllowance")
        self.Shellcourse1_2 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.Shellcourse1_2.setGeometry(QtCore.QRect(120, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Shellcourse1_2.setFont(font)
        self.Shellcourse1_2.setObjectName("Shellcourse1_2")
        self.heading_3 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.heading_3.setGeometry(QtCore.QRect(240, 20, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.heading_3.setFont(font)
        self.heading_3.setAutoFillBackground(True)
        self.heading_3.setFrameShape(QtWidgets.QFrame.Box)
        self.heading_3.setObjectName("heading_3")
        self.unit_10 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.unit_10.setGeometry(QtCore.QRect(600, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_10.setFont(font)
        self.unit_10.setObjectName("unit_10")
        self.Shellcourse1 = QtWidgets.QTextEdit(self.CorrsionAllowance)
        self.Shellcourse1.setGeometry(QtCore.QRect(370, 120, 211, 51))
        self.Shellcourse1.setObjectName("Shellcourse1")
        self.unit_11 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.unit_11.setGeometry(QtCore.QRect(600, 190, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_11.setFont(font)
        self.unit_11.setObjectName("unit_11")
        self.Shellcourse2 = QtWidgets.QTextEdit(self.CorrsionAllowance)
        self.Shellcourse2.setGeometry(QtCore.QRect(370, 190, 211, 51))
        self.Shellcourse2.setObjectName("Shellcourse2")
        self.Shellcourse2_3 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.Shellcourse2_3.setGeometry(QtCore.QRect(120, 190, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Shellcourse2_3.setFont(font)
        self.Shellcourse2_3.setObjectName("Shellcourse2_3")
        self.Bottom = QtWidgets.QLabel(self.CorrsionAllowance)
        self.Bottom.setGeometry(QtCore.QRect(120, 260, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Bottom.setFont(font)
        self.Bottom.setObjectName("Bottom")
        self.unit_12 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.unit_12.setGeometry(QtCore.QRect(600, 260, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_12.setFont(font)
        self.unit_12.setObjectName("unit_12")
        self.bottom = QtWidgets.QTextEdit(self.CorrsionAllowance)
        self.bottom.setGeometry(QtCore.QRect(370, 260, 211, 51))
        self.bottom.setObjectName("bottom")
        self.Ringofsketchplate_2 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.Ringofsketchplate_2.setGeometry(QtCore.QRect(120, 330, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Ringofsketchplate_2.setFont(font)
        self.Ringofsketchplate_2.setObjectName("Ringofsketchplate_2")
        self.unit_13 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.unit_13.setGeometry(QtCore.QRect(600, 330, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_13.setFont(font)
        self.unit_13.setObjectName("unit_13")
        self.Ringofsketchplate = QtWidgets.QTextEdit(self.CorrsionAllowance)
        self.Ringofsketchplate.setGeometry(QtCore.QRect(370, 330, 211, 51))
        self.Ringofsketchplate.setObjectName("Ringofsketchplate")
        self.Roof_2 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.Roof_2.setGeometry(QtCore.QRect(120, 400, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Roof_2.setFont(font)
        self.Roof_2.setObjectName("Roof_2")
        self.unit_14 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.unit_14.setGeometry(QtCore.QRect(600, 400, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_14.setFont(font)
        self.unit_14.setObjectName("unit_14")
        self.Roof = QtWidgets.QTextEdit(self.CorrsionAllowance)
        self.Roof.setGeometry(QtCore.QRect(370, 400, 211, 51))
        self.Roof.setObjectName("Roof")
        self.next_3 = QtWidgets.QPushButton(self.CorrsionAllowance)
        self.next_3.setGeometry(QtCore.QRect(530, 570, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next_3.setFont(font)
        self.next_3.setObjectName("next_3")
        self.previous_2 = QtWidgets.QPushButton(self.CorrsionAllowance)
        self.previous_2.setGeometry(QtCore.QRect(260, 570, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous_2.setFont(font)
        self.previous_2.setObjectName("previous_2")
        self.label_5 = QtWidgets.QLabel(self.CorrsionAllowance)
        self.label_5.setGeometry(QtCore.QRect(700, 30, 361, 271))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_5.setObjectName("label_5")
        StackedWidget.addWidget(self.CorrsionAllowance)
        self.InternalPressure = QtWidgets.QWidget()
        self.InternalPressure.setObjectName("InternalPressure")
        self.unit_18 = QtWidgets.QLabel(self.InternalPressure)
        self.unit_18.setGeometry(QtCore.QRect(350, 110, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_18.setFont(font)
        self.unit_18.setObjectName("unit_18")
        self.IPDesignconditionmmH2O = QtWidgets.QTextEdit(self.InternalPressure)
        self.IPDesignconditionmmH2O.setGeometry(QtCore.QRect(580, 170, 211, 51))
        self.IPDesignconditionmmH2O.setObjectName("IPDesignconditionmmH2O")
        self.heading_4 = QtWidgets.QLabel(self.InternalPressure)
        self.heading_4.setGeometry(QtCore.QRect(270, 20, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.heading_4.setFont(font)
        self.heading_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heading_4.setAutoFillBackground(True)
        self.heading_4.setFrameShape(QtWidgets.QFrame.Box)
        self.heading_4.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_4.setObjectName("heading_4")
        self.unit_19 = QtWidgets.QLabel(self.InternalPressure)
        self.unit_19.setGeometry(QtCore.QRect(610, 110, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_19.setFont(font)
        self.unit_19.setObjectName("unit_19")
        self.IPDesigncondition = QtWidgets.QLabel(self.InternalPressure)
        self.IPDesigncondition.setGeometry(QtCore.QRect(80, 170, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.IPDesigncondition.setFont(font)
        self.IPDesigncondition.setObjectName("IPDesigncondition")
        self.IPDesignconditionKpag = QtWidgets.QTextEdit(self.InternalPressure)
        self.IPDesignconditionKpag.setGeometry(QtCore.QRect(310, 170, 211, 51))
        self.IPDesignconditionKpag.setObjectName("IPDesignconditionKpag")
        self.IPOperatingconditionKpag = QtWidgets.QTextEdit(self.InternalPressure)
        self.IPOperatingconditionKpag.setGeometry(QtCore.QRect(310, 250, 211, 51))
        self.IPOperatingconditionKpag.setObjectName("IPOperatingconditionKpag")
        self.IPOperatingcondition = QtWidgets.QLabel(self.InternalPressure)
        self.IPOperatingcondition.setGeometry(QtCore.QRect(40, 250, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.IPOperatingcondition.setFont(font)
        self.IPOperatingcondition.setObjectName("IPOperatingcondition")
        self.IPOperatingconditionmmH2O = QtWidgets.QTextEdit(self.InternalPressure)
        self.IPOperatingconditionmmH2O.setGeometry(QtCore.QRect(580, 250, 211, 51))
        self.IPOperatingconditionmmH2O.setObjectName("IPOperatingconditionmmH2O")
        self.IPTestcondtionKpag = QtWidgets.QTextEdit(self.InternalPressure)
        self.IPTestcondtionKpag.setGeometry(QtCore.QRect(310, 330, 211, 51))
        self.IPTestcondtionKpag.setObjectName("IPTestcondtionKpag")
        self.IPTestcondtion = QtWidgets.QLabel(self.InternalPressure)
        self.IPTestcondtion.setGeometry(QtCore.QRect(100, 330, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.IPTestcondtion.setFont(font)
        self.IPTestcondtion.setObjectName("IPTestcondtion")
        self.IPTestcondtionmmH2O = QtWidgets.QTextEdit(self.InternalPressure)
        self.IPTestcondtionmmH2O.setGeometry(QtCore.QRect(580, 330, 211, 51))
        self.IPTestcondtionmmH2O.setObjectName("IPTestcondtionmmH2O")
        self.next_4 = QtWidgets.QPushButton(self.InternalPressure)
        self.next_4.setGeometry(QtCore.QRect(570, 530, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next_4.setFont(font)
        self.next_4.setObjectName("next_4")
        self.previous_3 = QtWidgets.QPushButton(self.InternalPressure)
        self.previous_3.setGeometry(QtCore.QRect(300, 530, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous_3.setFont(font)
        self.previous_3.setObjectName("previous_3")
        self.label_6 = QtWidgets.QLabel(self.InternalPressure)
        self.label_6.setGeometry(QtCore.QRect(750, -40, 341, 241))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_6.setObjectName("label_6")
        StackedWidget.addWidget(self.InternalPressure)
        self.ExternalPressure = QtWidgets.QWidget()
        self.ExternalPressure.setObjectName("ExternalPressure")
        self.heading_5 = QtWidgets.QLabel(self.ExternalPressure)
        self.heading_5.setGeometry(QtCore.QRect(240, 30, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.heading_5.setFont(font)
        self.heading_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heading_5.setAutoFillBackground(True)
        self.heading_5.setFrameShape(QtWidgets.QFrame.Box)
        self.heading_5.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_5.setObjectName("heading_5")
        self.EPDesignconditionKpag = QtWidgets.QTextEdit(self.ExternalPressure)
        self.EPDesignconditionKpag.setGeometry(QtCore.QRect(280, 180, 211, 51))
        self.EPDesignconditionKpag.setObjectName("EPDesignconditionKpag")
        self.EPOperatingcondition = QtWidgets.QLabel(self.ExternalPressure)
        self.EPOperatingcondition.setGeometry(QtCore.QRect(10, 260, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.EPOperatingcondition.setFont(font)
        self.EPOperatingcondition.setObjectName("EPOperatingcondition")
        self.EPDesigncondition = QtWidgets.QLabel(self.ExternalPressure)
        self.EPDesigncondition.setGeometry(QtCore.QRect(50, 180, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.EPDesigncondition.setFont(font)
        self.EPDesigncondition.setObjectName("EPDesigncondition")
        self.EPDesignconditionmmH2O = QtWidgets.QTextEdit(self.ExternalPressure)
        self.EPDesignconditionmmH2O.setGeometry(QtCore.QRect(550, 180, 211, 51))
        self.EPDesignconditionmmH2O.setObjectName("EPDesignconditionmmH2O")
        self.unit_20 = QtWidgets.QLabel(self.ExternalPressure)
        self.unit_20.setGeometry(QtCore.QRect(580, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_20.setFont(font)
        self.unit_20.setObjectName("unit_20")
        self.unit_21 = QtWidgets.QLabel(self.ExternalPressure)
        self.unit_21.setGeometry(QtCore.QRect(320, 120, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_21.setFont(font)
        self.unit_21.setObjectName("unit_21")
        self.EPOperatingconditionKpag = QtWidgets.QTextEdit(self.ExternalPressure)
        self.EPOperatingconditionKpag.setGeometry(QtCore.QRect(280, 260, 211, 51))
        self.EPOperatingconditionKpag.setObjectName("EPOperatingconditionKpag")
        self.EPOperatingconditionmmH2O = QtWidgets.QTextEdit(self.ExternalPressure)
        self.EPOperatingconditionmmH2O.setGeometry(QtCore.QRect(550, 260, 211, 51))
        self.EPOperatingconditionmmH2O.setObjectName("EPOperatingconditionmmH2O")
        self.next_5 = QtWidgets.QPushButton(self.ExternalPressure)
        self.next_5.setGeometry(QtCore.QRect(540, 430, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next_5.setFont(font)
        self.next_5.setObjectName("next_5")
        self.previous_4 = QtWidgets.QPushButton(self.ExternalPressure)
        self.previous_4.setGeometry(QtCore.QRect(270, 430, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous_4.setFont(font)
        self.previous_4.setObjectName("previous_4")
        self.label_7 = QtWidgets.QLabel(self.ExternalPressure)
        self.label_7.setGeometry(QtCore.QRect(720, -40, 351, 231))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_7.setObjectName("label_7")
        StackedWidget.addWidget(self.ExternalPressure)
        self.Temperature = QtWidgets.QWidget()
        self.Temperature.setObjectName("Temperature")
        self.TempOperatingconditionmin = QtWidgets.QTextEdit(self.Temperature)
        self.TempOperatingconditionmin.setGeometry(QtCore.QRect(350, 310, 211, 51))
        self.TempOperatingconditionmin.setObjectName("TempOperatingconditionmin")
        self.TempDesigncondition = QtWidgets.QLabel(self.Temperature)
        self.TempDesigncondition.setGeometry(QtCore.QRect(120, 170, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TempDesigncondition.setFont(font)
        self.TempDesigncondition.setObjectName("TempDesigncondition")
        self.unit_22 = QtWidgets.QLabel(self.Temperature)
        self.unit_22.setGeometry(QtCore.QRect(580, 170, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_22.setFont(font)
        self.unit_22.setObjectName("unit_22")
        self.TempDesigncondition_2 = QtWidgets.QTextEdit(self.Temperature)
        self.TempDesigncondition_2.setGeometry(QtCore.QRect(350, 170, 211, 51))
        self.TempDesigncondition_2.setObjectName("TempDesigncondition_2")
        self.TempOperatingcondition = QtWidgets.QLabel(self.Temperature)
        self.TempOperatingcondition.setGeometry(QtCore.QRect(80, 310, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TempOperatingcondition.setFont(font)
        self.TempOperatingcondition.setObjectName("TempOperatingcondition")
        self.label = QtWidgets.QLabel(self.Temperature)
        self.label.setGeometry(QtCore.QRect(280, 20, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.unit_23 = QtWidgets.QLabel(self.Temperature)
        self.unit_23.setGeometry(QtCore.QRect(400, 260, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_23.setFont(font)
        self.unit_23.setObjectName("unit_23")
        self.unit_24 = QtWidgets.QLabel(self.Temperature)
        self.unit_24.setGeometry(QtCore.QRect(650, 260, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_24.setFont(font)
        self.unit_24.setObjectName("unit_24")
        self.TempOperatingconditionmax = QtWidgets.QTextEdit(self.Temperature)
        self.TempOperatingconditionmax.setGeometry(QtCore.QRect(600, 310, 211, 51))
        self.TempOperatingconditionmax.setObjectName("TempOperatingconditionmax")
        self.Flashpoint = QtWidgets.QLabel(self.Temperature)
        self.Flashpoint.setGeometry(QtCore.QRect(180, 390, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Flashpoint.setFont(font)
        self.Flashpoint.setObjectName("Flashpoint")
        self.Flashpoint_2 = QtWidgets.QTextEdit(self.Temperature)
        self.Flashpoint_2.setGeometry(QtCore.QRect(350, 390, 211, 51))
        self.Flashpoint_2.setObjectName("Flashpoint_2")
        self.unit_26 = QtWidgets.QLabel(self.Temperature)
        self.unit_26.setGeometry(QtCore.QRect(580, 390, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_26.setFont(font)
        self.unit_26.setObjectName("unit_26")
        self.unit_25 = QtWidgets.QLabel(self.Temperature)
        self.unit_25.setGeometry(QtCore.QRect(830, 310, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_25.setFont(font)
        self.unit_25.setObjectName("unit_25")
        self.next_6 = QtWidgets.QPushButton(self.Temperature)
        self.next_6.setGeometry(QtCore.QRect(590, 570, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next_6.setFont(font)
        self.next_6.setObjectName("next_6")
        self.previous_5 = QtWidgets.QPushButton(self.Temperature)
        self.previous_5.setGeometry(QtCore.QRect(320, 570, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous_5.setFont(font)
        self.previous_5.setObjectName("previous_5")
        self.label_8 = QtWidgets.QLabel(self.Temperature)
        self.label_8.setGeometry(QtCore.QRect(730, -30, 351, 241))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_8.setObjectName("label_8")
        StackedWidget.addWidget(self.Temperature)
        self.OtherDesignData = QtWidgets.QWidget()
        self.OtherDesignData.setObjectName("OtherDesignData")
        self.Designliquidheight_3 = QtWidgets.QLabel(self.OtherDesignData)
        self.Designliquidheight_3.setGeometry(QtCore.QRect(180, 110, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Designliquidheight_3.setFont(font)
        self.Designliquidheight_3.setObjectName("Designliquidheight_3")
        self.label_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.unit_27 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_27.setGeometry(QtCore.QRect(670, 110, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_27.setFont(font)
        self.unit_27.setObjectName("unit_27")
        self.Designliquidheight = QtWidgets.QTextEdit(self.OtherDesignData)
        self.Designliquidheight.setGeometry(QtCore.QRect(440, 110, 211, 51))
        self.Designliquidheight.setObjectName("Designliquidheight")
        self.unit_28 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_28.setGeometry(QtCore.QRect(670, 180, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_28.setFont(font)
        self.unit_28.setObjectName("unit_28")
        self.Designspecificgravity = QtWidgets.QTextEdit(self.OtherDesignData)
        self.Designspecificgravity.setGeometry(QtCore.QRect(440, 180, 211, 51))
        self.Designspecificgravity.setObjectName("Designspecificgravity")
        self.Designspecificgravity_3 = QtWidgets.QLabel(self.OtherDesignData)
        self.Designspecificgravity_3.setGeometry(QtCore.QRect(150, 180, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Designspecificgravity_3.setFont(font)
        self.Designspecificgravity_3.setObjectName("Designspecificgravity_3")
        self.Designwindspeed = QtWidgets.QTextEdit(self.OtherDesignData)
        self.Designwindspeed.setGeometry(QtCore.QRect(440, 250, 211, 51))
        self.Designwindspeed.setObjectName("Designwindspeed")
        self.unit_29 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_29.setGeometry(QtCore.QRect(670, 250, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_29.setFont(font)
        self.unit_29.setObjectName("unit_29")
        self.Designwindspeed_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.Designwindspeed_2.setGeometry(QtCore.QRect(190, 240, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Designwindspeed_2.setFont(font)
        self.Designwindspeed_2.setObjectName("Designwindspeed_2")
        self.Seismicdesign = QtWidgets.QTextEdit(self.OtherDesignData)
        self.Seismicdesign.setGeometry(QtCore.QRect(440, 320, 211, 51))
        self.Seismicdesign.setObjectName("Seismicdesign")
        self.Seismicdesign_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.Seismicdesign_2.setGeometry(QtCore.QRect(240, 320, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Seismicdesign_2.setFont(font)
        self.Seismicdesign_2.setObjectName("Seismicdesign_2")
        self.Typeofroof = QtWidgets.QTextEdit(self.OtherDesignData)
        self.Typeofroof.setGeometry(QtCore.QRect(440, 390, 211, 51))
        self.Typeofroof.setObjectName("Typeofroof")
        self.Typeofroof_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.Typeofroof_2.setGeometry(QtCore.QRect(270, 390, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Typeofroof_2.setFont(font)
        self.Typeofroof_2.setObjectName("Typeofroof_2")
        self.Frangibleroof_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.Frangibleroof_2.setGeometry(QtCore.QRect(250, 460, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Frangibleroof_2.setFont(font)
        self.Frangibleroof_2.setObjectName("Frangibleroof_2")
        self.HHLL = QtWidgets.QTextEdit(self.OtherDesignData)
        self.HHLL.setGeometry(QtCore.QRect(440, 530, 211, 51))
        self.HHLL.setObjectName("HHLL")
        self.unit_33 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_33.setGeometry(QtCore.QRect(670, 530, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_33.setFont(font)
        self.unit_33.setObjectName("unit_33")
        self.HHLL_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.HHLL_2.setGeometry(QtCore.QRect(170, 530, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HHLL_2.setFont(font)
        self.HHLL_2.setObjectName("HHLL_2")
        self.Designwindspeed_3 = QtWidgets.QLabel(self.OtherDesignData)
        self.Designwindspeed_3.setGeometry(QtCore.QRect(190, 270, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Designwindspeed_3.setFont(font)
        self.Designwindspeed_3.setObjectName("Designwindspeed_3")
        self.HLL = QtWidgets.QTextEdit(self.OtherDesignData)
        self.HLL.setGeometry(QtCore.QRect(440, 600, 211, 51))
        self.HLL.setObjectName("HLL")
        self.HLL_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.HLL_2.setGeometry(QtCore.QRect(230, 600, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HLL_2.setFont(font)
        self.HLL_2.setObjectName("HLL_2")
        self.unit_34 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_34.setGeometry(QtCore.QRect(670, 600, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_34.setFont(font)
        self.unit_34.setObjectName("unit_34")
        self.LLL = QtWidgets.QTextEdit(self.OtherDesignData)
        self.LLL.setGeometry(QtCore.QRect(440, 670, 211, 51))
        self.LLL.setObjectName("LLL")
        self.LLL_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.LLL_2.setGeometry(QtCore.QRect(240, 670, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LLL_2.setFont(font)
        self.LLL_2.setObjectName("LLL_2")
        self.unit_35 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_35.setGeometry(QtCore.QRect(670, 670, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_35.setFont(font)
        self.unit_35.setObjectName("unit_35")
        self.LLLL = QtWidgets.QTextEdit(self.OtherDesignData)
        self.LLLL.setGeometry(QtCore.QRect(440, 740, 211, 51))
        self.LLLL.setObjectName("LLLL")
        self.LLLL_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.LLLL_2.setGeometry(QtCore.QRect(190, 740, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LLLL_2.setFont(font)
        self.LLLL_2.setObjectName("LLLL_2")
        self.unit_36 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_36.setGeometry(QtCore.QRect(670, 740, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_36.setFont(font)
        self.unit_36.setObjectName("unit_36")
        self.minThicknessbyclient = QtWidgets.QTextEdit(self.OtherDesignData)
        self.minThicknessbyclient.setGeometry(QtCore.QRect(440, 810, 211, 51))
        self.minThicknessbyclient.setObjectName("minThicknessbyclient")
        self.minThicknessbyclient_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.minThicknessbyclient_2.setGeometry(QtCore.QRect(140, 810, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.minThicknessbyclient_2.setFont(font)
        self.minThicknessbyclient_2.setObjectName("minThicknessbyclient_2")
        self.unit_37 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_37.setGeometry(QtCore.QRect(670, 810, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_37.setFont(font)
        self.unit_37.setObjectName("unit_37")
        self.unit_38 = QtWidgets.QLabel(self.OtherDesignData)
        self.unit_38.setGeometry(QtCore.QRect(670, 880, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_38.setFont(font)
        self.unit_38.setObjectName("unit_38")
        self.minAnnularThicknessbyclient_2 = QtWidgets.QLabel(self.OtherDesignData)
        self.minAnnularThicknessbyclient_2.setGeometry(QtCore.QRect(40, 880, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.minAnnularThicknessbyclient_2.setFont(font)
        self.minAnnularThicknessbyclient_2.setObjectName("minAnnularThicknessbyclient_2")
        self.minAnnularThicknessbyclient = QtWidgets.QTextEdit(self.OtherDesignData)
        self.minAnnularThicknessbyclient.setGeometry(QtCore.QRect(440, 880, 211, 51))
        self.minAnnularThicknessbyclient.setObjectName("minAnnularThicknessbyclient")
        self.Frangibleroof = QtWidgets.QTextEdit(self.OtherDesignData)
        self.Frangibleroof.setGeometry(QtCore.QRect(440, 460, 211, 51))
        self.Frangibleroof.setObjectName("Frangibleroof")
        self.next_7 = QtWidgets.QPushButton(self.OtherDesignData)
        self.next_7.setGeometry(QtCore.QRect(550, 960, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next_7.setFont(font)
        self.next_7.setObjectName("next_7")
        self.previous_6 = QtWidgets.QPushButton(self.OtherDesignData)
        self.previous_6.setGeometry(QtCore.QRect(280, 960, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous_6.setFont(font)
        self.previous_6.setObjectName("previous_6")
        self.label_9 = QtWidgets.QLabel(self.OtherDesignData)
        self.label_9.setGeometry(QtCore.QRect(720, -60, 361, 271))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../download (1).png"))
        self.label_9.setObjectName("label_9")
        StackedWidget.addWidget(self.OtherDesignData)
        self.ShellPlate = QtWidgets.QWidget()
        self.ShellPlate.setObjectName("ShellPlate")
        self.ShellPlateCourse1Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse1Material.setGeometry(QtCore.QRect(300, 170, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse1Material.setFont(font)
        self.ShellPlateCourse1Material.setObjectName("ShellPlateCourse1Material")
        self.ShellPlateCourse1Material.addItem("")
        self.ShellPlateCourse1Material.addItem("")
        self.ShellPlateCourse2Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse2Material.setGeometry(QtCore.QRect(300, 230, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse2Material.setFont(font)
        self.ShellPlateCourse2Material.setObjectName("ShellPlateCourse2Material")
        self.ShellPlateCourse2Material.addItem("")
        self.ShellPlateCourse2Material.addItem("")
        self.ShellPlateCourse3Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse3Material.setGeometry(QtCore.QRect(300, 290, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse3Material.setFont(font)
        self.ShellPlateCourse3Material.setObjectName("ShellPlateCourse3Material")
        self.ShellPlateCourse3Material.addItem("")
        self.ShellPlateCourse3Material.addItem("")
        self.ShellPlateCourse4Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse4Material.setGeometry(QtCore.QRect(300, 350, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse4Material.setFont(font)
        self.ShellPlateCourse4Material.setObjectName("ShellPlateCourse4Material")
        self.ShellPlateCourse4Material.addItem("")
        self.ShellPlateCourse4Material.addItem("")
        self.ShellPlateCourse5Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse5Material.setGeometry(QtCore.QRect(300, 410, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse5Material.setFont(font)
        self.ShellPlateCourse5Material.setObjectName("ShellPlateCourse5Material")
        self.ShellPlateCourse5Material.addItem("")
        self.ShellPlateCourse5Material.addItem("")
        self.ShellPlateCourse6Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse6Material.setGeometry(QtCore.QRect(300, 460, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse6Material.setFont(font)
        self.ShellPlateCourse6Material.setObjectName("ShellPlateCourse6Material")
        self.ShellPlateCourse6Material.addItem("")
        self.ShellPlateCourse6Material.addItem("")
        self.ShellPlateCourse7Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse7Material.setGeometry(QtCore.QRect(300, 520, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse7Material.setFont(font)
        self.ShellPlateCourse7Material.setObjectName("ShellPlateCourse7Material")
        self.ShellPlateCourse7Material.addItem("")
        self.ShellPlateCourse7Material.addItem("")
        self.ShellPlateCourse8Material = QtWidgets.QComboBox(self.ShellPlate)
        self.ShellPlateCourse8Material.setGeometry(QtCore.QRect(300, 570, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShellPlateCourse8Material.setFont(font)
        self.ShellPlateCourse8Material.setObjectName("ShellPlateCourse8Material")
        self.ShellPlateCourse8Material.addItem("")
        self.ShellPlateCourse8Material.addItem("")
        self.ShellPlateCourse1Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse1Material_2.setGeometry(QtCore.QRect(150, 170, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse1Material_2.setFont(font)
        self.ShellPlateCourse1Material_2.setObjectName("ShellPlateCourse1Material_2")
        self.ShellPlateCourse2Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse2Material_2.setGeometry(QtCore.QRect(150, 230, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse2Material_2.setFont(font)
        self.ShellPlateCourse2Material_2.setObjectName("ShellPlateCourse2Material_2")
        self.ShellPlateCourse3Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse3Material_2.setGeometry(QtCore.QRect(150, 290, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse3Material_2.setFont(font)
        self.ShellPlateCourse3Material_2.setObjectName("ShellPlateCourse3Material_2")
        self.ShellPlateCourse4Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse4Material_2.setGeometry(QtCore.QRect(150, 350, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse4Material_2.setFont(font)
        self.ShellPlateCourse4Material_2.setObjectName("ShellPlateCourse4Material_2")
        self.ShellPlateCourse5Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse5Material_2.setGeometry(QtCore.QRect(150, 410, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse5Material_2.setFont(font)
        self.ShellPlateCourse5Material_2.setObjectName("ShellPlateCourse5Material_2")
        self.ShellPlateCourse6Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse6Material_2.setGeometry(QtCore.QRect(150, 460, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse6Material_2.setFont(font)
        self.ShellPlateCourse6Material_2.setObjectName("ShellPlateCourse6Material_2")
        self.ShellPlateCourse7Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse7Material_2.setGeometry(QtCore.QRect(150, 520, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse7Material_2.setFont(font)
        self.ShellPlateCourse7Material_2.setObjectName("ShellPlateCourse7Material_2")
        self.ShellPlateCourse8Material_2 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse8Material_2.setGeometry(QtCore.QRect(150, 570, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse8Material_2.setFont(font)
        self.ShellPlateCourse8Material_2.setObjectName("ShellPlateCourse8Material_2")
        self.ShellPlateCourse1CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse1CA.setGeometry(QtCore.QRect(660, 170, 301, 61))
        self.ShellPlateCourse1CA.setObjectName("ShellPlateCourse1CA")
        self.ShellPlateCourse2CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse2CA.setGeometry(QtCore.QRect(660, 230, 301, 61))
        self.ShellPlateCourse2CA.setObjectName("ShellPlateCourse2CA")
        self.ShellPlateCourse3CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse3CA.setGeometry(QtCore.QRect(660, 290, 301, 61))
        self.ShellPlateCourse3CA.setObjectName("ShellPlateCourse3CA")
        self.ShellPlateCourse4CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse4CA.setGeometry(QtCore.QRect(660, 350, 301, 61))
        self.ShellPlateCourse4CA.setObjectName("ShellPlateCourse4CA")
        self.ShellPlateCourse5CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse5CA.setGeometry(QtCore.QRect(660, 410, 301, 51))
        self.ShellPlateCourse5CA.setObjectName("ShellPlateCourse5CA")
        self.ShellPlateCourse6CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse6CA.setGeometry(QtCore.QRect(660, 460, 301, 61))
        self.ShellPlateCourse6CA.setObjectName("ShellPlateCourse6CA")
        self.ShellPlateCourse7CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse7CA.setGeometry(QtCore.QRect(660, 520, 301, 51))
        self.ShellPlateCourse7CA.setObjectName("ShellPlateCourse7CA")
        self.ShellPlateCourse8CA = QtWidgets.QTextEdit(self.ShellPlate)
        self.ShellPlateCourse8CA.setGeometry(QtCore.QRect(660, 570, 301, 61))
        self.ShellPlateCourse8CA.setObjectName("ShellPlateCourse8CA")
        self.Designliquidheight_19 = QtWidgets.QLabel(self.ShellPlate)
        self.Designliquidheight_19.setGeometry(QtCore.QRect(140, 120, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Designliquidheight_19.setFont(font)
        self.Designliquidheight_19.setObjectName("Designliquidheight_19")
        self.Designliquidheight_20 = QtWidgets.QLabel(self.ShellPlate)
        self.Designliquidheight_20.setGeometry(QtCore.QRect(400, 120, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Designliquidheight_20.setFont(font)
        self.Designliquidheight_20.setObjectName("Designliquidheight_20")
        self.Designliquidheight_21 = QtWidgets.QLabel(self.ShellPlate)
        self.Designliquidheight_21.setGeometry(QtCore.QRect(670, 120, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Designliquidheight_21.setFont(font)
        self.Designliquidheight_21.setObjectName("Designliquidheight_21")
        self.line = QtWidgets.QFrame(self.ShellPlate)
        self.line.setGeometry(QtCore.QRect(110, 130, 20, 501))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.ShellPlate)
        self.line_2.setGeometry(QtCore.QRect(120, 120, 841, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.ShellPlate)
        self.line_3.setGeometry(QtCore.QRect(290, 130, 20, 501))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.ShellPlate)
        self.line_4.setGeometry(QtCore.QRect(650, 130, 20, 501))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.ShellPlate)
        self.line_5.setGeometry(QtCore.QRect(950, 130, 20, 501))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.ShellPlate)
        self.line_6.setGeometry(QtCore.QRect(120, 160, 841, 16))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(4)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.ShellPlate)
        self.line_7.setGeometry(QtCore.QRect(120, 220, 841, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(4)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.ShellPlate)
        self.line_8.setGeometry(QtCore.QRect(120, 280, 841, 16))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(4)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.ShellPlate)
        self.line_9.setGeometry(QtCore.QRect(120, 340, 841, 16))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(4)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.ShellPlate)
        self.line_10.setGeometry(QtCore.QRect(120, 400, 841, 16))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(4)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.ShellPlate)
        self.line_11.setGeometry(QtCore.QRect(120, 450, 841, 16))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(4)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.ShellPlate)
        self.line_12.setGeometry(QtCore.QRect(120, 510, 841, 16))
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(4)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.ShellPlate)
        self.line_13.setGeometry(QtCore.QRect(120, 620, 841, 16))
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(4)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.ShellPlate)
        self.line_14.setGeometry(QtCore.QRect(120, 560, 841, 16))
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.ShellPlateData = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateData.setGeometry(QtCore.QRect(300, 30, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateData.setFont(font)
        self.ShellPlateData.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ShellPlateData.setAutoFillBackground(True)
        self.ShellPlateData.setFrameShape(QtWidgets.QFrame.Box)
        self.ShellPlateData.setAlignment(QtCore.Qt.AlignCenter)
        self.ShellPlateData.setObjectName("ShellPlateData")
        self.TankDesignCalculator = QtWidgets.QPushButton(self.ShellPlate)
        self.TankDesignCalculator.setGeometry(QtCore.QRect(530, 710, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.TankDesignCalculator.setFont(font)
        self.TankDesignCalculator.setObjectName("TankDesignCalculator")
        self.OutputPath = QtWidgets.QTextEdit(self.ShellPlate)
        self.OutputPath.setGeometry(QtCore.QRect(170, 840, 791, 87))
        self.OutputPath.setObjectName("OutputPath")
        self.ShellPlateCourse8Material_3 = QtWidgets.QLabel(self.ShellPlate)
        self.ShellPlateCourse8Material_3.setGeometry(QtCore.QRect(10, 860, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ShellPlateCourse8Material_3.setFont(font)
        self.ShellPlateCourse8Material_3.setObjectName("ShellPlateCourse8Material_3")
        self.previous_7 = QtWidgets.QPushButton(self.ShellPlate)
        self.previous_7.setGeometry(QtCore.QRect(170, 720, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.previous_7.setFont(font)
        self.previous_7.setObjectName("previous_7")
        self.ShellPlateCourse1Material.raise_()
        self.ShellPlateCourse2Material.raise_()
        self.ShellPlateCourse3Material.raise_()
        self.ShellPlateCourse4Material.raise_()
        self.ShellPlateCourse5Material.raise_()
        self.ShellPlateCourse6Material.raise_()
        self.ShellPlateCourse7Material.raise_()
        self.ShellPlateCourse8Material.raise_()
        self.ShellPlateCourse1Material_2.raise_()
        self.ShellPlateCourse2Material_2.raise_()
        self.ShellPlateCourse3Material_2.raise_()
        self.ShellPlateCourse4Material_2.raise_()
        self.ShellPlateCourse5Material_2.raise_()
        self.ShellPlateCourse6Material_2.raise_()
        self.ShellPlateCourse7Material_2.raise_()
        self.ShellPlateCourse8Material_2.raise_()
        self.ShellPlateCourse1CA.raise_()
        self.ShellPlateCourse2CA.raise_()
        self.ShellPlateCourse3CA.raise_()
        self.ShellPlateCourse4CA.raise_()
        self.ShellPlateCourse5CA.raise_()
        self.ShellPlateCourse6CA.raise_()
        self.ShellPlateCourse7CA.raise_()
        self.ShellPlateCourse8CA.raise_()
        self.Designliquidheight_19.raise_()
        self.Designliquidheight_20.raise_()
        self.Designliquidheight_21.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.ShellPlateData.raise_()
        self.TankDesignCalculator.raise_()
        self.OutputPath.raise_()
        self.ShellPlateCourse8Material_3.raise_()
        self.previous_7.raise_()
        StackedWidget.addWidget(self.ShellPlate)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        self.next.clicked.connect(lambda : StackedWidget.setCurrentIndex(1))
        self.previous.clicked.connect(lambda : StackedWidget.setCurrentIndex(0))
        self.next_2.clicked.connect(lambda : StackedWidget.setCurrentIndex(2))
        self.previous_2.clicked.connect(lambda : StackedWidget.setCurrentIndex(1))
        self.next_3.clicked.connect(lambda : StackedWidget.setCurrentIndex(3))
        self.previous_3.clicked.connect(lambda : StackedWidget.setCurrentIndex(2))
        self.next_4.clicked.connect(lambda : StackedWidget.setCurrentIndex(4))
        self.previous_4.clicked.connect(lambda : StackedWidget.setCurrentIndex(3))
        self.next_5.clicked.connect(lambda : StackedWidget.setCurrentIndex(5))
        self.previous_5.clicked.connect(lambda : StackedWidget.setCurrentIndex(4))
        self.next_6.clicked.connect(lambda : StackedWidget.setCurrentIndex(6))
        self.previous_6.clicked.connect(lambda : StackedWidget.setCurrentIndex(5))
        self.next_7.clicked.connect(lambda : StackedWidget.setCurrentIndex(7))
        self.previous_7.clicked.connect(lambda : StackedWidget.setCurrentIndex(6))
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)
        self.TankDesignCalculator.clicked.connect(self.TankDesignCal)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.Tankspecficationdata_2.setText(_translate("StackedWidget", "Tank specfication data :"))
        self.Tanknumber_2.setText(_translate("StackedWidget", "Tank number :"))
        self.Typeoftank_2.setText(_translate("StackedWidget", "Type of tank :"))
        self.Itemname_2.setText(_translate("StackedWidget", "Item name :"))
        self.Designcode_2.setText(_translate("StackedWidget", "Desing code :"))
        self.heading.setText(_translate("StackedWidget", "Tank Design Data"))
        self.next.setText(_translate("StackedWidget", "Next"))
        self.heading_2.setText(_translate("StackedWidget", "Design Input Parameter"))
        self.Nominalcapacity_2.setText(_translate("StackedWidget", "Nominal capacity :"))
        self.Insidediameter_2.setText(_translate("StackedWidget", "Inside diameter :"))
        self.tankheight_2.setText(_translate("StackedWidget", "Tank height :"))
        self.maximumfillingheight_2.setText(_translate("StackedWidget", "Maximum filling height :"))
        self.Htest_2.setText(_translate("StackedWidget", "Htest :"))
        self.infillingrate_2.setText(_translate("StackedWidget", "In-filling rate:"))
        self.Emptyingrate_2.setText(_translate("StackedWidget", "Emptying rate :"))
        self.Productdensity20C_2.setText(_translate("StackedWidget", "Product density @20C :"))
        self.Slopeatthebottom1_2.setText(_translate("StackedWidget", "Slope at the bottom 1:"))
        self.unit.setText(_translate("StackedWidget", "cubicmeter"))
        self.unit_2.setText(_translate("StackedWidget", "meter"))
        self.unit_3.setText(_translate("StackedWidget", "meter"))
        self.unit_4.setText(_translate("StackedWidget", "meter"))
        self.unit_5.setText(_translate("StackedWidget", "meter"))
        self.unit_6.setText(_translate("StackedWidget", "cubicmeter per meter"))
        self.unit_7.setText(_translate("StackedWidget", "cubicmeter per meter"))
        self.unit_8.setText(_translate("StackedWidget", "kg per cubicmeter "))
        self.unit_9.setText(_translate("StackedWidget", "(means 1 in 120)"))
        self.next_2.setText(_translate("StackedWidget", "Next"))
        self.previous.setText(_translate("StackedWidget", "Previous"))
        self.Shellcourse1_2.setText(_translate("StackedWidget", "Shell (1st course) :"))
        self.heading_3.setText(_translate("StackedWidget", "Corrsion Allowance date"))
        self.unit_10.setText(_translate("StackedWidget", "mm"))
        self.unit_11.setText(_translate("StackedWidget", "mm"))
        self.Shellcourse2_3.setText(_translate("StackedWidget", "Shell (2nd course) :"))
        self.Bottom.setText(_translate("StackedWidget", "Bottom:"))
        self.unit_12.setText(_translate("StackedWidget", "mm"))
        self.Ringofsketchplate_2.setText(_translate("StackedWidget", "Ring of sketch plate :"))
        self.unit_13.setText(_translate("StackedWidget", "mm"))
        self.Roof_2.setText(_translate("StackedWidget", "Roof :"))
        self.unit_14.setText(_translate("StackedWidget", "mm"))
        self.next_3.setText(_translate("StackedWidget", "Next"))
        self.previous_2.setText(_translate("StackedWidget", "Previous"))
        self.unit_18.setText(_translate("StackedWidget", "In KPa g"))
        self.heading_4.setText(_translate("StackedWidget", "Internal Pressure"))
        self.unit_19.setText(_translate("StackedWidget", "In mm H20"))
        self.IPDesigncondition.setText(_translate("StackedWidget", "Design condition :"))
        self.IPOperatingcondition.setText(_translate("StackedWidget", "Operating condition :"))
        self.IPTestcondtion.setText(_translate("StackedWidget", "Test condition :"))
        self.next_4.setText(_translate("StackedWidget", "Next"))
        self.previous_3.setText(_translate("StackedWidget", "Previous"))
        self.heading_5.setText(_translate("StackedWidget", "External Pressure"))
        self.EPOperatingcondition.setText(_translate("StackedWidget", "Operating condition :"))
        self.EPDesigncondition.setText(_translate("StackedWidget", "Design condition :"))
        self.unit_20.setText(_translate("StackedWidget", "In mm H20"))
        self.unit_21.setText(_translate("StackedWidget", "In KPa g"))
        self.next_5.setText(_translate("StackedWidget", "Next"))
        self.previous_4.setText(_translate("StackedWidget", "Previous"))
        self.TempDesigncondition.setText(_translate("StackedWidget", "Design condition :"))
        self.unit_22.setText(_translate("StackedWidget", "Celsius"))
        self.TempOperatingcondition.setText(_translate("StackedWidget", "Operating condition :"))
        self.label.setText(_translate("StackedWidget", "Temperature"))
        self.unit_23.setText(_translate("StackedWidget", "Minimum"))
        self.unit_24.setText(_translate("StackedWidget", "Maximum"))
        self.Flashpoint.setText(_translate("StackedWidget", "Flash point :"))
        self.unit_26.setText(_translate("StackedWidget", "Celsius"))
        self.unit_25.setText(_translate("StackedWidget", "Celsius"))
        self.next_6.setText(_translate("StackedWidget", "Next"))
        self.previous_5.setText(_translate("StackedWidget", "Previous"))
        self.Designliquidheight_3.setText(_translate("StackedWidget", "Design liquid height :"))
        self.label_2.setText(_translate("StackedWidget", "Other Design Data"))
        self.unit_27.setText(_translate("StackedWidget", "m"))
        self.unit_28.setText(_translate("StackedWidget", "unit"))
        self.Designspecificgravity_3.setText(_translate("StackedWidget", "Design specific gravity :"))
        self.unit_29.setText(_translate("StackedWidget", "m per sec"))
        self.Designwindspeed_2.setText(_translate("StackedWidget", "Design wind speed :"))
        self.Seismicdesign_2.setText(_translate("StackedWidget", "Seismic design :"))
        self.Typeofroof_2.setText(_translate("StackedWidget", "Type of roof :"))
        self.Frangibleroof_2.setText(_translate("StackedWidget", "Frangible roof :"))
        self.unit_33.setText(_translate("StackedWidget", "m"))
        self.HHLL_2.setText(_translate("StackedWidget", "High-high liquid level :"))
        self.Designwindspeed_3.setText(_translate("StackedWidget", " (3 sec gust wind speed)"))
        self.HLL_2.setText(_translate("StackedWidget", "High liquid level :"))
        self.unit_34.setText(_translate("StackedWidget", "m"))
        self.LLL_2.setText(_translate("StackedWidget", "Low liquid level :"))
        self.unit_35.setText(_translate("StackedWidget", "m"))
        self.LLLL_2.setText(_translate("StackedWidget", "low Low liquid level :"))
        self.unit_36.setText(_translate("StackedWidget", "m"))
        self.minThicknessbyclient_2.setText(_translate("StackedWidget", "min. Thickness by client :"))
        self.unit_37.setText(_translate("StackedWidget", "m"))
        self.unit_38.setText(_translate("StackedWidget", "m"))
        self.minAnnularThicknessbyclient_2.setText(_translate("StackedWidget", "min. Annular Thickness by client :"))
        self.next_7.setText(_translate("StackedWidget", "Next"))
        self.previous_6.setText(_translate("StackedWidget", "Previous"))
        self.ShellPlateCourse1Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse1Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse2Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse2Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse3Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse3Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse4Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse4Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse5Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse5Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse6Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse6Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse7Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse7Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse8Material.setItemText(0, _translate("StackedWidget", "A573 Gr.70 "))
        self.ShellPlateCourse8Material.setItemText(1, _translate("StackedWidget", "A283 Gr. C"))
        self.ShellPlateCourse1Material_2.setText(_translate("StackedWidget", "Course 1 :"))
        self.ShellPlateCourse2Material_2.setText(_translate("StackedWidget", "Course 2 :"))
        self.ShellPlateCourse3Material_2.setText(_translate("StackedWidget", "Course 3 :"))
        self.ShellPlateCourse4Material_2.setText(_translate("StackedWidget", "Course 4 :"))
        self.ShellPlateCourse5Material_2.setText(_translate("StackedWidget", "Course 5 :"))
        self.ShellPlateCourse6Material_2.setText(_translate("StackedWidget", "Course 6 :"))
        self.ShellPlateCourse7Material_2.setText(_translate("StackedWidget", "Course 7 :"))
        self.ShellPlateCourse8Material_2.setText(_translate("StackedWidget", "Course 8 :"))
        self.Designliquidheight_19.setText(_translate("StackedWidget", "Shell plate"))
        self.Designliquidheight_20.setText(_translate("StackedWidget", "materials"))
        self.Designliquidheight_21.setText(_translate("StackedWidget", "Corrsion allowances (mm)"))
        self.ShellPlateData.setText(_translate("StackedWidget", "Shell Plate Data"))
        self.TankDesignCalculator.setText(_translate("StackedWidget", "Submit"))
        self.ShellPlateCourse8Material_3.setText(_translate("StackedWidget", "Output Path :"))
        self.previous_7.setText(_translate("StackedWidget", "Previous"))
    def TankDesignCal(self):
         Tanknumber=str(self.Tanknumber.toPlainText())
         Typeoftank=str(self.Typeoftank.toPlainText())
         Itemname=str(self.Itemname.toPlainText())
         Designcode=str(self.Designcode.toPlainText())
         Nominalcapacity=float(self.Nominalcapacity.toPlainText())
         Insidediameter=float(self.Insidediameter.toPlainText())
         tankheight=float(self.tankheight.toPlainText())
         maximumfillingheight=float(self.maximumfillingheight.toPlainText())
         Htest=float(self.Htest.toPlainText())
         infillingrate=float(self.infillingrate.toPlainText())
         Emptyingrate=float(self.Emptyingrate.toPlainText())
         Productdensity20C=float(self.Productdensity20C.toPlainText())
         Slopeatthebottom1=float(self.Slopeatthebottom1.toPlainText())
         Shellcourse1=float(self.Shellcourse1.toPlainText())
         Shellcourse2=float(self.Shellcourse2.toPlainText())
         bottom=float(self.bottom.toPlainText())
         Ringofsketchplate=float(self.Ringofsketchplate.toPlainText())
         Roof=float(self.Roof.toPlainText())
         IPDesignconditionKpag=float(self.IPDesignconditionKpag.toPlainText())
         IPDesignconditionmmH2O=float(self.IPDesignconditionmmH2O.toPlainText())
         IPOperatingconditionKpag=float(self.IPOperatingconditionKpag.toPlainText())
         IPOperatingconditionmmH2O=float(self.IPOperatingconditionmmH2O.toPlainText())
         IPTestcondtionKpag=float(self.IPTestcondtionKpag.toPlainText())
         IPTestcondtionmmH2O=float(self.IPTestcondtionmmH2O.toPlainText())
         EPDesignconditionKpag=float(self.EPDesignconditionKpag.toPlainText())
         EPDesignconditionmmH2O=float(self.EPDesignconditionmmH2O.toPlainText())
         EPOperatingconditionKpag=float(self.EPOperatingconditionmmH2O.toPlainText())
         EPOperatingconditionmmH2O=float(self.EPOperatingconditionmmH2O.toPlainText())
         TempDesigncondition=float(self.TempDesigncondition.toPlainText())
         TempOperatingconditionmin=float(self.TempOperatingconditionmin.toPlainText())
         TempOperatingconditionmax=float(self.TempOperatingconditionmax.toPlainText())
         Flashpoint=float(self.Flashpoint.toPlainText())
         Designliquidheight=float(self.Designliquidheight.toPlainText())
         Designspecificgravity=float(self.Designspecificgravity.toPlainText())
         Designwindspeed=float(self.Designwindspeed.toPlainText())
         Seismicdesign=str(self.Seismicdesign.toPlainText())
         Typeofroof=str(self.Typeofroof.toPlainText())
         Frangibleroof=str(self.Frangibleroof.toPlainText())
         HHLL=float(self.HHLL.toPlainText())
         HLL=float(self.HLL.toPlainText())
         LLL=float(self.LLL.toPlainText())
         LLLL=float(self.LLLL.toPlainText())
         minThicknessbyclient=float(self.minThicknessbyclient.toPlainText())
         minAnnularThicknessbyclient=float(self.minAnnularThicknessbyclient.toPlainText())
         ShellPlateCourse1Material=str(self.ShellPlateCourse1Material.currentText())
         ShellPlateCourse1CA=float(self.ShellPlateCourse1CA.toPlainText())
         ShellPlateCourse2Material=str(self.ShellPlateCourse2Material.currentText())
         ShellPlateCourse2CA=float(self.ShellPlateCourse2CA.toPlainText())
         ShellPlateCourse3Material=str(self.ShellPlateCourse3Material.currentText())
         ShellPlateCourse3CA=float(self.ShellPlateCourse3CA.toPlainText())
         ShellPlateCourse4Material=str(self.ShellPlateCourse4Material.currentText())
         ShellPlateCourse4CA=float(self.ShellPlateCourse4CA.toPlainText())
         ShellPlateCourse5Material=str(self.ShellPlateCourse5Material.currentText())
         ShellPlateCourse5CA=float(self.ShellPlateCourse5CA.toPlainText())
         ShellPlateCourse6Material=str(self.ShellPlateCourse6Material.currentText())
         ShellPlateCourse6CA=float(self.ShellPlateCourse6CA.toPlainText())
         ShellPlateCourse7Material=str(self.ShellPlateCourse7Material.currentText())
         ShellPlateCourse7CA=float(self.ShellPlateCourse7CA.toPlainText())
         ShellPlateCourse8Material=str(self.ShellPlateCourse8Material.currentText())
         ShellPlateCourse8CA=float(self.ShellPlateCourse8CA.toPlainText())
         
         
#        price = int(self.price_box.toPlainText())
#        tax = (self.tax_rate.value())
#        total_price = price  + ((tax / 100) * price)
#        total_price_string = "The total price with tax is: " + str(total_price)
#        self.results_window.setText(total_price_string)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StackedWidget = QtWidgets.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())

